-- MySQL Script generated by MySQL Workbench
-- sam. 22 juin 2019 15:27:01 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PurBeurre
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PurBeurre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PurBeurre` ;
USE `PurBeurre` ;

-- -----------------------------------------------------
-- Table `PurBeurre`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PurBeurre`.`Category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHdsqdsqAR(45) NULL COMMENT 'categories',
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PurBeurre`.`Food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PurBeurre`.`Food` (
  `food_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `food_name` VARCHAR(80) NULL COMMENT 'product_name',
  `ingredients_text` MEDIUMTEXT NULL,
  `store` VARCHAR(45) NULL COMMENT 'stores',
  `off_link` VARCHAR(255) NULL COMMENT 'url',
  `nutriscore` TINYTEXT NULL COMMENT 'nutrition-score-fr_100g',
  PRIMARY KEY (`food_id`, `category_id`),
  INDEX `fk_Food_1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Food_1`
    FOREIGN KEY (`category_id`)
    REFERENCES `PurBeurre`.`Category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PurBeurre`.`History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PurBeurre`.`History` (
  `history_id` INT NOT NULL,
  `food_id` INT NULL,
  `surrogate_id` INT NULL,
  PRIMARY KEY (`history_id`),
  INDEX `fk_History_2_idx` (`surrogate_id` ASC) VISIBLE,
  CONSTRAINT `fk_History_1`
    FOREIGN KEY (`surrogate_id`)
    REFERENCES `PurBeurre`.`Food` (`food_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_History_2`
    FOREIGN KEY (`surrogate_id`)
    REFERENCES `PurBeurre`.`Food` (`food_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
