-- MySQL Script generated by MySQL Workbench
-- mer. 21 août 2019 00:24:47 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PurBeurre
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PurBeurre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PurBeurre` ;
USE `PurBeurre` ;

